#ifndef SRC_BASE_INTERNAL_VM_THREAD_LOCAL_H_
#define SRC_BASE_INTERNAL_VM_THREAD_LOCAL_H_

#ifndef FLUFFOS_OWNER_THREAD_VM
#define FLUFFOS_OWNER_THREAD_VM 1
#endif

#if FLUFFOS_OWNER_THREAD_VM
#define FLUFFOS_VM_THREAD_LOCAL thread_local
#else
#define FLUFFOS_VM_THREAD_LOCAL
#endif

#endif /* SRC_BASE_INTERNAL_VM_THREAD_LOCAL_H_ */
